### ISSUE TITLE
mycrossword + Exolve?

### ISSUE THREAD

**Issue by viresh-ratnakar** [t-blackwell/mycrossword#38]
I think mycrossword.co.uk is awesome!

You've clearly put a lot of good effort into the solver interface (https://github.com/t-blackwell/mycrossword). I should know, because I have put in a lot of effort doing similar things in Exolve (https://github.com/viresh-ratnakar/exolve) :-).

I think it is totally fine to have such multiple efforts go on in parallel, occasionally picking up ideas from each other. Both the projects are open-source, which is great.

We should at least briefly and periodically consider the possibility of collaborating, imo.

I think Exolve can easily be a snap-in infrastructure that can be used to do the interactive solving part in mycrossword. I'm not sure if you've looked at the Exolve format, but it is a pretty simple plaintext format. And it supports loads of tiny and big features that are currently not there in mycrossword (afaik). A few examples:

- Clue numbers are right-aligned and formatted as in a newspaper, including when there are linked clues
- 3-d crosswords.
- Barred grids, diagramless squares, circles, colours, ninas.
- Creating 2- or 3-column PDFs formatted similar to newspapers.
- Annotations that can be revealed inline within clues.
- Arbitrary languages.
- Taking notes on the crossword (overall/per-clue) to be provided as feedback (I use this extensively when test-solving)
- Support for an accessibility interface ("webifi") that is text-only and can be used with audio.
- Non-numeric clue labels
- Automatic conversion of just the text of the clues to a solvable grid (i.e., automatic inference of the grid)
 
You can experiment with the idea by simply _adding_ support for Exolve-based puzzles in addition to the current interface. I can help with coding the changes if needed. Exolve can be easily customized to any look-and-feel.

And of course, along similar lines, Exet can be used for powering the construction interface, but we can discuss that separately/later (unless that intrigues you more).

Cheers,
Viresh

**Comment by t-blackwell** [comment]
Hi Viresh

I have previously considered whether it makes sense for us to collaborate and came to the conclusion it's not that straightforward for a few reasons:

- React vs vanilla JS - I can't easily add non-React components to a React application. It goes against the design principles. I get the impression that it would be a huge effort to convert your 8K line HTML file to make it compatible.
- Data formats - we both use different structures for our crossword data. Whenever a puzzle is imported into the system I convert it to JSON and insert its meta data, template and clues into the database. The setting UI is tightly coupled with data model design, therefore if I were to switch to Exolve & Exet (you'd almost certainly need both), assuming they were made to be compatible with React, it would still require a great deal of replumbing to work with the back-end - time which I don't have.
- Different approaches - Exolve is pretty powerful and has lots of nice features but I wouldn't want to opt into all of those features. For instance, I restrict lots of elements to keep the UI clean and consistent i.e. grid sizes, types, styles etc. As far as I can tell Exolve is all or nothing; it's not modular in the sense of being able to switch off certain aspects.

You're completely right though, it is a shame to have similar goals and to work independently in parallel. I'm just not sure what a collaboration would look like that doesn't involve one person throwing away great swathes their code and doing a massive rewrite.

Tom

**Comment by viresh-ratnakar** [comment]
Hi Tom,

Thanks. Yeah, I figured something like this would be the story :-).

If you like some Exolve feature sufficiently at any time to want to add it to mycrossword, please feel free to reach out and I can implement it for you, time permitting (I haven't used React, but I can surely pick it up).

I'll close with a quick feature request (which actually triggered this whole chain of thought for me :-)), I was solving the Platypus puzzle using the desktop interface (https://mycrossword.co.uk/cryptic/792#22-down). Once you get past 19d, the clues are not visible above the fold, unless you scroll down. I think you should enable the "current clue is displayed above the grid" functionality on desktop too (I believe you have it on mobile). Thanks!

**Comment by t-blackwell** [comment]
I did consider this early on in the design but decided that I didn't particularly like the duplication when the clue's in the viewport. Plus, when there's an extra `<div>` at the top I would either have a misalignment between the grid and the clues or a band of whitespace which feels a bit wasteful. FMMV

![image](https://user-images.githubusercontent.com/31444631/199648320-90c4a8cf-2eac-4ef8-a31b-0307cc437260.png)

The UI behaves differently at the various breakpoints and one of them bounds the clues into scrollable containers. One thing I did wonder was whether this should be the default behaviour as this would solve the problem you're describing...

![breakpoint](https://user-images.githubusercontent.com/31444631/199649385-fb8d6894-49e8-41c8-96fc-5e27ff11869a.gif)

**Comment by viresh-ratnakar** [comment]
Imo, once you have access to the clue on top of the grid, you quickly stop looking at / worrying about the clue lists most of the time, leading to a simpler experience that's focused around the grid. The full list of clues is there to glance at, when needed, esp. to get a sense of which ones are not yet solved. I see your point about the whitespace band looking a bit disconcerting, but I think if you put thin horizontal lines at the top of the two clue columns, lined up with the top of the grid, it looks just fine, imo (that's how I have it in Exolve, see [example](https://viresh-ratnakar.github.io/thc/gussalufz-thc-05-2022-grid-2-29-clues.html)).

But yeah, if absolutely you do not want the clue on top, then making the clue lists be scrollable containers by default would be good, I think.

**Comment by t-blackwell** [comment]
FYI I've made the clue list containers scrollable when on xxl, xl and lg viewports - see [commit ca27d](https://github.com/t-blackwell/mycrossword/commit/ca27d4dc2fefd9e91ca02d8c8c661c8b80934868). I've updated the main site to use the new version and will be pushing it out on 01/01/2023.
